// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Loads .env.local first (secrets, not committed), then .env (template).
// override:false (default) => the first loaded value wins, so .env.local takes
// precedence over .env for DATABASE_URL.
config({ path: ".env.local" });
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI only (migrate/db). Prefer the DIRECT (unpooled) Neon connection: the
    // advisory lock `migrate deploy` takes is unreliable through the -pooler
    // endpoint (P1002 lock timeout). Falls back to the pooled URL when unset.
    // The runtime app keeps using DATABASE_URL (pooled) via the Neon adapter
    // (lib/prisma.ts) — this does not affect it.
    url:
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["POSTGRES_URL_NON_POOLING"] ??
      process.env["DATABASE_URL"],
  },
});
